name: Docker deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - composer-version: 1
            tags: |
              type=semver,pattern={{version}}-v1
              type=raw,pattern=v1
            latest: false
          - composer-version: 2
            tags: |
              type=semver,pattern={{version}}-v2
              type=semver,pattern={{version}}
              type=raw,pattern=v2
            latest: true
    steps:
      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Generate metadata
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          image: eliashaeussler/composer-update-check
          flavor: |
            latest=${{ matrix.latest }}
          tags: ${{ matrix.tags }}

      # Prepare build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login at Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            COMPOSER_VERSION=${{ matrix.composer-version }}
          tags: ${{ steps.meta.outputs.tags }}
