name: Release

on:
  push:
    tags:
      - '*'

jobs:
  docs:
    name: 'Build and deploy documentation'
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.pages-url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: pages
      cancel-in-progress: true

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@e567077243633adfcfd38b5e5af5a8a10983b27a # 1.1.5

      - name: 'Build docs'
        env:
          COMPOSE_FILE: build/docs/docker-compose.yaml
        run: |
          docker-compose build --pull
          docker-compose run --rm docs build

      - name: 'Deploy docs'
        id: deploy
        uses: eliashaeussler/gha/.github/actions/deploy-pages@e567077243633adfcfd38b5e5af5a8a10983b27a # 1.1.5
        with:
          base-path: 'site'

  release:
    name: 'Create release'
    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@e567077243633adfcfd38b5e5af5a8a10983b27a # 1.1.5
    permissions:
      contents: write
