name: Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  # Job: Run unit tests
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, Composer ${{ matrix.composer-version }} & ${{ matrix.preferred-install }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.1", "7.2", "7.3", "7.4", "8.0"]
        composer-version: ["1", "2"]
        preferred-install: ["stable", "lowest"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Define Composer cache
      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Define Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: tests-php-${{ matrix.php-version }}-${{ matrix.composer-version }}-${{ matrix.preferred-install }}
          restore-keys: |
            tests-php-${{ matrix.php-version }}-${{ matrix.composer-version }}-
            tests-php-${{ matrix.php-version }}-
            tests-php-

      # Install dependencies
      - name: Install Composer and dependencies
        run: |
          composer config platform.composer-plugin-api "${{ matrix.composer-version }}.99"
          composer config platform.composer-runtime-api "${{ matrix.composer-version }}.99"
          composer update --no-progress --prefer-${{ matrix.preferred-install }} --with "composer/composer:^${{ matrix.composer-version }}"
          composer self-update --${{ matrix.composer-version }}

      # Run tests
      - name: Build coverage directory
        run: mkdir -p .build/coverage
      - name: Run tests
        run: composer test

  # Job: Collect and report test coverage
  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: pcov

      # Define Composer cache
      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Define Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: tests-php-8.0-stable
          restore-keys: |
            tests-php-8.0-
            tests-php-

      # Install dependencies
      - name: Install Composer and dependencies
        run: composer update --no-progress

      # Run tests
      - name: Build coverage directory
        run: mkdir -p .build/coverage
      - name: Run tests with coverage
        run: composer test:coverage

      # Report coverage
      - name: Fix coverage path
        working-directory: .build/coverage
        run: sed -i 's#/home/runner/work/composer-update-check/composer-update-check#${{ github.workspace }}#g' clover.xml
      - name: CodeClimate report
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/.build/coverage/clover.xml:clover
      - name: codecov report
        uses: codecov/codecov-action@v3
        with:
          directory: .build/coverage
          fail_ci_if_error: true
          verbose: true

  # Job: Run Docker tests
  tests-docker:
    name: Tests with Docker (PHP ${{ matrix.php-version }} & Composer ${{ matrix.composer-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.1", "7.2", "7.3", "7.4", "8.0"]
        composer-version: ["1", "2"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run tests
      - name: Run tests
        run: ./bin/run-docker-tests.sh --composer-version "${{ matrix.composer-version }}" --php-version "${{ matrix.php-version }}"

  # Job: Run unit tests of composer-update-reporter
  tests-reporter:
    name: Tests of eliashaeussler/composer-update-reporter
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - id: set-branch
        run: echo "::set-output name=branch::${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}"
      - id: set-sha
        run: echo "::set-output name=sha::${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}"
      - name: Trigger workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 'Tests for composer-update-check'
          token: ${{ secrets.PAT_REPORTER_TRIGGER }}
          repo: eliashaeussler/composer-update-reporter
          ref: 'main'
          inputs: '{ "update-check-branch": "${{ steps.set-branch.outputs.branch }}", "update-check-sha": "${{ steps.set-sha.outputs.sha }}" }'
